### ISSUE TITLE
[BUG] Settings Icon

### ISSUE THREAD

**Issue by LilQwack** [DiscordStyles/iPadOS#10]
**Describe the bug:**  
Icon not showing like its just plain white square

**Screenshots:**  
![Screen Shot 2021-08-23 at 7 54 34 PM](https://user-images.githubusercontent.com/77838600/130450804-61928e48-4237-4374-9728-e828f5594faa.png)
![Screen Shot 2021-08-23 at 7 54 40 PM](https://user-images.githubusercontent.com/77838600/130450823-84efceac-3baa-4206-9b60-fcf080be2ec8.png)

**Infomation:**  
Discord channel: Canary
OS: OSX
Mod: Powercord and BDcompat plugin
Discord language: English  

**Additional context:**  
uh i use the theme from (git clone https://github.com/DiscordStyles/iPadOS) and the icon just turn to be white square but when i use the theme from downloading the css and convert it to powercord theme by https://convert.creatable.cafe/ it works fine
![Screen Shot 2021-08-23 at 8 02 18 PM](https://user-images.githubusercontent.com/77838600/130451777-a554fb9e-916b-4a86-b235-cb6e7748daad.png)
pic above the one I'm using from converting the theme

**Comment by Gibbu** [comment]
Hmmmmm.. Most likely because Powercord doesn't have a autoprefixer meaning it's not adding the required css rules.
Not much I can do about that without breaking it for other platform. Expect for just changing the `powercord_manifest.json` `theme` property.
