### ISSUE TITLE
Theme Unusable

### ISSUE THREAD

**Issue by bc9** [DiscordStyles/iPadOS#13]
Restarted my discord client today and my theme didn't come on after boot, so I went to settings to ensure it was enabled and it was. Tried playing around with settings a little bit to see if it was an error on my end, but after several client and computer restarts I'm concluding it's an issue with the base css page no longer existing.

`https://discordstyles.github.io/iPadOS/dist/iPadOS.css` is no longer a valid URL and I can only assume this is what is causing the issue.

**Comment by Gibbu** [comment]
Fixed.
