### ISSUE TITLE
Suggestion: Separate user and server icons' border radii from global, button and input border radii

### ISSUE THREAD

**Issue by kamekku14** [DiscordStyles/iPadOS#4]
Echoing from <https://github.com/DiscordStyles/Slate/issues/1>, I know if it's possible if we could have options for user avatars' and server/guild icons' roundness.

**Comment by Gibbu** [comment]
I can do that.

**Comment by Gibbu** [comment]
I added:
`--avatar-radius` and `--server-radius` variables. They're both defaulted to `--rounded-large`.
