### ISSUE TITLE
Server Settings Role

### ISSUE THREAD

**Issue by LilQwack** [DiscordStyles/iPadOS#9]
[BUG] Edit Role ui bugged out

Describe the bug:
Edit role UI messed up when I'm trying to edit some roles

Screenshots: 
![Screen Shot 2021-08-16 at 8 32 48 AM](https://user-images.githubusercontent.com/77838600/129500391-6f1b9d76-dcbb-4a61-b140-66082c41c6a0.png) 
https://imgur.com/jvdFnwD

Infomation (please complete the following information):
Discord channel: Canary
OS: OSX 
Mod: BetterDiscord/Powercord (mainly powercord and using bdcompat for betterdiscord plugin)
Discord language: English

**Comment by Gibbu** [comment]
Nah, that's by design. :)

Fixed it though.
